---
titulo: Título de la tesis

documentclass: apa7
classoption:
  - doc
  - a4paper
  - 12pt
  - spanish
  - biblatex

lang: es-ES

linestretch: 1.5
indent: 0.5in

bibliography: references.bib
csl: format/apa7.csl

header-includes: |
  \usepackage{tocloft, ragged2e, pdflscape, longtable, csvsimple}
  \geometry{margin=1in}

  \newcommand{\listannexesname}{\large Lista de anexos}
  \newlistof{annexes}{loa}{\listannexesname}

  \addtocontents{toc}{\protect\thispagestyle{empty}}
  \addtocontents{lof}{\protect\thispagestyle{empty}}
  \addtocontents{lot}{\protect\thispagestyle{empty}}
  \addtocontents{loa}{\protect\thispagestyle{empty}}

  \newcounter{figuras}
  \newcommand\figura[2]{
      \phantomsection\refstepcounter{figuras}
      \addcontentsline{lof}{subsection}{Figura \arabic{figuras}. #2}\textbf{Figura \arabic{figuras}}\label{#1}\hfill\break\textit{#2}}

  \newcounter{tablas}
  \newcommand\tabla[2]{
      \phantomsection\refstepcounter{tablas}
      \addcontentsline{lot}{subsection}{Tabla \arabic{tablas}. #2}\textbf{Tabla \arabic{tablas}}\label{#1}\hfill\break\textit{#2}}

  \newcounter{anexos}
  \newcommand\anexo[2]{
      \phantomsection\refstepcounter{anexos}
      \addcontentsline{loa}{subsection}{Anexo \arabic{anexos}. #2}\textbf{Anexo \arabic{anexos}\label{#1}.\ \textit{#2}}}

  \newcommand\tsv[1]{
      {\tiny\csvautolongtable[respect all, separator=tab]{#1.tsv}}}

  \def\titulo{Título de la tesis}
  \def\facultad{Facultad de Ciencias Empresariales}
  \def\escuela{Escuala de Contabilidad}
  \def\autor{Nombres Apellidos}
  \def\grado{Contador Público}
  \def\fecha{Chiclayo, 2022}
  \def\asesorNombre{Nombres Apellidos}
  \def\asesorOrcid{https://orcid.org/0000-0000-0000-0000}
  \def\presidente{Nombres Apellidos}
  \def\secretario{Nombres Apellidos}
  \def\vocal{Nombre Apellidos}
---

